const THEMES={
  "backtoschool": {
    "name": "Back to School",
    "emoji": "🎒 ✏️",
    "colors": [
      "#F7DFA1",
      "#8E6A52"
    ],
    "character": "pencil",
    "words": [
      "PENCIL",
      "ERASER",
      "CRAYON",
      "MARKER",
      "PAPER",
      "FOLDER",
      "BACKPACK",
      "TEACHER",
      "STUDENT",
      "SCHOOL",
      "CLASSROOM",
      "DESK",
      "CHAIR",
      "BOOK",
      "LIBRARY",
      "RECESS",
      "LUNCH",
      "RULER",
      "SCISSORS",
      "GLUE",
      "NOTEBOOK",
      "CALENDAR",
      "COMPUTER",
      "READING",
      "WRITING",
      "MATH",
      "SCIENCE",
      "ART",
      "MUSIC",
      "FRIEND"
    ]
  },
  "fall": {
    "name": "Fall",
    "emoji": "🍂 🍎",
    "colors": [
      "#EBC79B",
      "#A86643"
    ],
    "character": "scarecrow",
    "words": [
      "AUTUMN",
      "LEAVES",
      "ACORN",
      "APPLE",
      "ORCHARD",
      "PUMPKIN",
      "HARVEST",
      "SCARECROW",
      "HAYRIDE",
      "CORN",
      "SWEATER",
      "JACKET",
      "BREEZE",
      "FOREST",
      "MAPLE",
      "OAK",
      "RAKE",
      "BASKET",
      "FARM",
      "CIDER",
      "SUNFLOWER",
      "SQUIRREL",
      "PINECONE",
      "FOOTBALL",
      "SEPTEMBER",
      "OCTOBER",
      "NOVEMBER",
      "CRUNCHY",
      "GOLDEN",
      "COZY"
    ]
  },
  "halloween": {
    "name": "Halloween",
    "emoji": "🎃 👻",
    "colors": [
      "#F0B584",
      "#815B82"
    ],
    "character": "ghost",
    "words": [
      "PUMPKIN",
      "COSTUME",
      "CANDY",
      "GHOST",
      "BAT",
      "WITCH",
      "BROOM",
      "SPIDER",
      "WEB",
      "MONSTER",
      "MUMMY",
      "SKELETON",
      "MASK",
      "PARTY",
      "TREAT",
      "TRICK",
      "HAUNTED",
      "MOON",
      "BLACK CAT",
      "CAULDRON",
      "CAPE",
      "VAMPIRE",
      "OWL",
      "LANTERN",
      "BOO",
      "CORN MAZE",
      "POTION",
      "CREEPY",
      "NIGHT",
      "CANDY CORN"
    ]
  },
  "thanksgiving": {
    "name": "Thanksgiving",
    "emoji": "🦃 🥧",
    "colors": [
      "#E5CFAD",
      "#9A6A45"
    ],
    "character": "turkey",
    "words": [
      "TURKEY",
      "THANKFUL",
      "FAMILY",
      "DINNER",
      "FEAST",
      "PIE",
      "GRAVY",
      "STUFFING",
      "POTATO",
      "CORN",
      "HARVEST",
      "AUTUMN",
      "PUMPKIN",
      "CRANBERRY",
      "PARADE",
      "NOVEMBER",
      "TABLE",
      "PLATE",
      "FORK",
      "NAPKIN",
      "ROLLS",
      "CARROTS",
      "APPLE PIE",
      "GATHER",
      "SHARE",
      "KINDNESS",
      "FRIENDS",
      "HOME",
      "COOKING",
      "GRATEFUL"
    ]
  },
  "christmas": {
    "name": "Christmas",
    "emoji": "🎄 🎁",
    "colors": [
      "#CFE5D7",
      "#A95E58"
    ],
    "character": "gingerbread",
    "words": [
      "CHRISTMAS",
      "SANTA",
      "REINDEER",
      "SLEIGH",
      "ELF",
      "PRESENT",
      "GIFT",
      "TREE",
      "ORNAMENT",
      "STAR",
      "LIGHTS",
      "STOCKING",
      "WREATH",
      "CANDY CANE",
      "GINGERBREAD",
      "COOKIE",
      "SNOW",
      "BELLS",
      "CAROL",
      "CHIMNEY",
      "NORTH POLE",
      "RIBBON",
      "HOLIDAY",
      "DECEMBER",
      "TOY",
      "MITTENS",
      "COCOA",
      "FAMILY",
      "CHEER",
      "WORKSHOP"
    ]
  },
  "winter": {
    "name": "Winter",
    "emoji": "❄️ ⛄",
    "colors": [
      "#C6E3F2",
      "#6E9EB7"
    ],
    "character": "snowman",
    "words": [
      "WINTER",
      "SNOW",
      "SNOWMAN",
      "SNOWFLAKE",
      "MITTENS",
      "SCARF",
      "BOOTS",
      "COAT",
      "SLED",
      "ICE",
      "ICICLE",
      "FROST",
      "FREEZE",
      "CHILLY",
      "COLD",
      "COCOA",
      "BLANKET",
      "PENGUIN",
      "POLAR BEAR",
      "SKATES",
      "SKATING",
      "SWEATER",
      "HAT",
      "FIREPLACE",
      "JANUARY",
      "FEBRUARY",
      "FLURRY",
      "SNOWBALL",
      "IGLOO",
      "BLIZZARD"
    ]
  },
  "valentine": {
    "name": "Valentine",
    "emoji": "💗 💌",
    "colors": [
      "#F2CCD4",
      "#B9677D"
    ],
    "character": "heart",
    "words": [
      "VALENTINE",
      "HEART",
      "LOVE",
      "FRIEND",
      "KINDNESS",
      "CARD",
      "FLOWER",
      "ROSE",
      "CHOCOLATE",
      "CANDY",
      "CUPID",
      "FEBRUARY",
      "PINK",
      "RED",
      "HUG",
      "SMILE",
      "SWEET",
      "FRIENDSHIP",
      "CARING",
      "SHARE",
      "KIND",
      "HAPPY",
      "LETTER",
      "ENVELOPE",
      "RIBBON",
      "GIFT",
      "HEARTS",
      "BE MINE",
      "XOXO",
      "CELEBRATE"
    ]
  },
  "stpatrick": {
    "name": "St. Patrick",
    "emoji": "☘️ 🌈",
    "colors": [
      "#D2E9C1",
      "#5F9164"
    ],
    "character": "leprechaun",
    "words": [
      "SHAMROCK",
      "GREEN",
      "RAINBOW",
      "GOLD",
      "LEPRECHAUN",
      "IRELAND",
      "CLOVER",
      "LUCKY",
      "MARCH",
      "POT OF GOLD",
      "COINS",
      "HAT",
      "PARADE",
      "DANCE",
      "MUSIC",
      "MAGIC",
      "SPRING",
      "TREASURE",
      "HORSESHOE",
      "JIG",
      "IRISH",
      "EMERALD",
      "CASTLE",
      "HARP",
      "FLAG",
      "FRIEND",
      "CELEBRATE",
      "LUCK",
      "RAIN",
      "BOOTS"
    ]
  },
  "earthday": {
    "name": "Earth Day",
    "emoji": "🌎 🌱",
    "colors": [
      "#C8E7E7",
      "#4F8B7B"
    ],
    "character": "earth",
    "words": [
      "EARTH",
      "PLANET",
      "RECYCLE",
      "REUSE",
      "REDUCE",
      "NATURE",
      "OCEAN",
      "FOREST",
      "TREE",
      "FLOWER",
      "GARDEN",
      "WATER",
      "CLEAN",
      "GREEN",
      "ENERGY",
      "SOLAR",
      "WIND",
      "ANIMAL",
      "HABITAT",
      "COMPOST",
      "TRASH",
      "PARK",
      "RIVER",
      "BEACH",
      "PLANT",
      "SEED",
      "APRIL",
      "PROTECT",
      "CONSERVE",
      "ENVIRONMENT"
    ]
  },
  "spring": {
    "name": "Spring",
    "emoji": "🌷 🐝",
    "colors": [
      "#DCECC8",
      "#7BA069"
    ],
    "character": "flower",
    "words": [
      "SPRING",
      "FLOWER",
      "RAIN",
      "RAINBOW",
      "GARDEN",
      "SEED",
      "PLANT",
      "BLOSSOM",
      "BUTTERFLY",
      "BEE",
      "BIRD",
      "NEST",
      "PUDDLE",
      "UMBRELLA",
      "BOOTS",
      "SUNSHINE",
      "GRASS",
      "TULIP",
      "DAISY",
      "CLOUD",
      "WORM",
      "LADYBUG",
      "PICNIC",
      "MARCH",
      "APRIL",
      "MAY",
      "WARM",
      "GROW",
      "GREEN",
      "BLOOM"
    ]
  },
  "summer": {
    "name": "Summer",
    "emoji": "☀️ 🍉",
    "colors": [
      "#F7E0A0",
      "#D48C53"
    ],
    "character": "sun",
    "words": [
      "SUMMER",
      "SUN",
      "BEACH",
      "OCEAN",
      "SAND",
      "SWIM",
      "POOL",
      "VACATION",
      "PICNIC",
      "CAMP",
      "CAMPING",
      "SUNSCREEN",
      "HAT",
      "SHORTS",
      "SANDALS",
      "WATERMELON",
      "LEMONADE",
      "ICE CREAM",
      "POPSICLE",
      "SHELL",
      "WAVES",
      "SURF",
      "JUNE",
      "JULY",
      "AUGUST",
      "SUNSHINE",
      "HOT",
      "PALM TREE",
      "KITE",
      "ADVENTURE"
    ]
  }
};